---
- name: Apply common configuration to all hosts
  hosts: kafka_host
  # become: yes # Removed as per user request
  tags:
    - common
  roles:
    - common

- name: Deploy JMX Exporter
  hosts: jmx_exporter_host
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/jmx_exporter.yml
  tags:
    - jmx_exporter
  roles:
    - jmx_exporter

- name: Deploy Zookeeper Cluster
  hosts: zookeeper_host
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/jmx_exporter.yml
    - ../group_vars/zookeeper.yml
  tags: 
    - zookeeper
  roles:
    - zookeeper

- name: Deploy Kafka Cluster
  hosts: kafka_host
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/jmx_exporter.yml
    - ../group_vars/kafka.yml
  tags: 
    - kafka
  roles:
    - kafka

- name: Deploy Logstash Cluster
  hosts: logstash_host
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/jmx_exporter.yml
    - ../group_vars/logstash.yml
  tags:
    - logstash
  roles:
    - logstash

- name: Deploy Elasticsearch Cluster
  hosts: elasticsearch_host
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/jmx_exporter.yml
    - ../group_vars/elasticsearch.yml
  tags:
    - elasticsearch
  roles:
    - elasticsearch

#- name: Deploy Kibana Cluster
#  hosts: kibana_host
#  become: true
#  serial: 1
#  vars_files:
#    - ../group_vars/all.yml
#    - ../group_vars/jmx_exporter.yml
#    - ../group_vars/kibana.yml
#  tags:
#    - kibana
#  roles:
#    - kibana

- name: Deploy Flink Cluster
  hosts: flink_host
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/jmx_exporter.yml
    - ../group_vars/flink.yml
  tags:
    - flink
  roles:
    - flink