---
- name: Apply common configuration to all hosts
  hosts: server_cluster
  # become: yes # Removed as per user request
  tags:
    - common
  roles:
    - common

- name: Deploy JMX Exporter
  hosts: jmx_exporter
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/jmx_exporter.yml
  tags:
    - jmx_exporter
  roles:
    - jmx_exporter

- name: Deploy Zookeeper Cluster
  hosts: zookeeper
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/jmx_exporter.yml
    - ../group_vars/zookeeper.yml
  tags: 
    - zookeeper
  roles:
    - zookeeper

- name: Deploy Kafka Cluster
  hosts: kafka
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/jmx_exporter.yml
    - ../group_vars/kafka.yml
  tags: 
    - kafka
  roles:
    - kafka

- name: Deploy Flink Cluster
  hosts: flink
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/flink.yml
  tags:
    - flink
  roles:
    - flink